# Generated by Django 5.0 on 2023-12-08 09:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("uploaded", models.BooleanField(default=False)),
                ("original_name", models.CharField(max_length=150)),
                ("original_mime_type", models.CharField(max_length=10)),
                ("original_md5", models.CharField(max_length=32)),
                ("is_mozjpeg_available", models.BooleanField(default=False)),
                ("is_webp_available", models.BooleanField(default=False)),
                ("is_avif_available", models.BooleanField(default=False)),
            ],
        ),
    ]
