# Generated by Django 5.0 on 2024-06-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_authorizationkeys_image_height_image_model_version_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuthorizationKeys",
            new_name="AuthorizationKey",
        ),
        migrations.RenameField(
            model_name="authorizationkey",
            old_name="can_convert",
            new_name="can_upload_variant",
        ),
    ]
