# Generated by Django 5.0 on 2024-06-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_rename_authorizationkeys_authorizationkey_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authorizationkey",
            old_name="can_upload",
            new_name="can_upload_image",
        ),
    ]
