# Generated by Django 5.0 on 2024-06-26 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_rename_can_upload_authorizationkey_can_upload_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageVariantTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("height", models.IntegerField()),
                ("width", models.IntegerField()),
                ("original_file_type", models.CharField(max_length=10)),
                ("file_type", models.CharField(max_length=10)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="images.image"
                    ),
                ),
            ],
        ),
    ]
